### PR TITLE
Add ejbca demo using docker

### PR DESCRIPTION
**Pull request by rajeev-0**
## Motivation

add demo with latest EJBCA Community edition docker image. 

## Proposed Changes

ejbca-test.yml: add ejbca test workflow
Makefile_v1: update EJBCA demo using docker.
demo_EJBCA.cnf: fetch crl from server.
EJBCA_docker.env, demo_EJBCA.cnf, {CMP,CUSTOMER,TLS}_ROOTCA.pem: add files for testing EJBCA demo using docker.

## Test Plan

No code change.

### CODE REVIEW

**Review by DDvO — CHANGES_REQUESTED** [review]
I've had a closer look and re-worked the EJBCA demo, combining it with the existing one, which can use the Playground EJBCA. This was pretty awkward to do, but finally I succeeded.
I also squashed part of the commits.

Looks like the CRLs produced by the dockered EJBCA are not up-to-date:
```
cmpClient:(unknown function)():src/credentials/store.c:576: WARNING: CRL issued by /CN=CUSTOMER_ISSUING_CA has expired
cmpClient:(unknown function)():src/credentials/store.c:576: WARNING: CRL issued by /CN=CMP_ROOTCA has expired
cmpClient:(unknown function)():src/credentials/store.c:576: WARNING: CRL issued by /CN=TLS_ROOTCA has expired
```
Is there an easy way of kicking the EJBCA instance to produce fresh CRLs?

**Comment by rajeev-0** [comment]
> I've had a closer look and re-worked the EJBCA demo, combining it with the existing one, which can use the Playground EJBCA. This was pretty awkward to do, but finally I succeeded. I also squashed part of the commits.
> 
> Looks like the CRLs produced by the dockered EJBCA are not up-to-date:
> 
> ```
> cmpClient:(unknown function)():src/credentials/store.c:576: WARNING: CRL issued by /CN=CUSTOMER_ISSUING_CA has expired
> cmpClient:(unknown function)():src/credentials/store.c:576: WARNING: CRL issued by /CN=CMP_ROOTCA has expired
> cmpClient:(unknown function)():src/credentials/store.c:576: WARNING: CRL issued by /CN=TLS_ROOTCA has expired
> ```
> 
> Is there an easy way of kicking the EJBCA instance to produce fresh CRLs?

There are workers which can be configured in live system, But I am not sure about docker. I will look into this and hopefully be able to produce fresh CRLs.

**Comment by DDvO** [comment]
Rebased on the latest master,
and extended `README.md` to mention both flavors of the demo: with Insta and EJBCA.
Unfortunately, when launching the Docker instance of EJBCA, it takes very long to become usable.
Therefore, I did not choose it as the default.

**Comment by DDvO** [comment]
Note that I managed to make use of TLS when connecting to the EJBCA in the docker
although it uses an ephemeral self-signed TLS server cert, by retrieving this cert and random server name using `openssl s_client` just after launching.

**Pull request merged**
