### PR TITLE
Improve help message

### PR DESCRIPTION
**Pull request by RufusJWB**
## Motivation

Improve documentation. Took us ages to find the list of allowed algorithms

## Proposed Changes

Link to openssl header file in which the algorithms are defined.

## Test Plan

n/a

### CODE REVIEW

**Comment by DDvO** [comment]
Thank you also for this PR.

Hints on which MAC algorithms are available would have been found in the man page or online documentation,
as also written in the `README.md`:

> The CLI use with the available options are documented in [`cmpClient.pod`](../tree/master/doc/cmpClient.pod).

I am not sure if the link https://raw.githubusercontent.com/openssl/openssl/master/include/openssl/obj_mac.h that you suggested to add would be sufficiently simple to use and provides better info than the text given there:

> To get the names of supported MAC algorithms use B<openssl list -mac-algorithms>
and possibly combine such a name with the name of a supported digest algorithm,
e.g., hmacWithSHA256.
Defaults to C<hmac-sha1> as per RFC 4210.

Moreover, the CLI help output needs to be very brief and should not have overlong lines.
So I suggest modifying the PR as follows:

* add to `cmpClient.c` after the existing text for `-mac` just a line like
```
    OPT_MORE("See the man page or online doc for hints on available algorithms"),
 ```
 * as far as you still see value in the providing that above URL, please add it to `doc/cmpClient.pod`.

**Comment by RufusJWB** [comment]
@DDvO I updated my PR based on your proposal. Please double check. But honestly, I don't find the man-page helpful. Take for example 

image

Why is one algorithm called `hmacWithSHA256` but the other `hmac-sha1`. And why is `hmac-sha256` not working but `hmac-sha3-224`?

**Comment by DDvO** [comment]
> @DDvO I updated my PR based on your proposal. Please double check.

Looks good - nice that you added it for both `-mac` and `-digest`.

> But honestly, I don't find the man-page helpful. Take for example
> 
> image
> 
> Why is one algorithm called `hmacWithSHA256` but the other `hmac-sha1`? And why is `hmac-sha256` not working but `hmac-sha3-224`?

This is most likely due to the legacy and wonders of ITEF & IANA standardization.
As finding a supported combination of names is not straightforward, I hinted at also possibly adding the URL you gave to `cmpClient.pod`.
I suggest adding there before the line
```
Defaults to C<hmac-sha1> as per RFC 4210.
```
something like
```
L<https://raw.githubusercontent.com/openssl/openssl/master/include/openssl/obj_mac.h>
contains the complete set of combinations of MAC and digest algorithm names.
```

**Comment by RufusJWB** [comment]
@DDvO please double check again.

**Review by DDvO — APPROVED** [review]
LGTM - thanks for contributing.

**Pull request merged**
