### PR TITLE
Various CMake tweaks

### PR DESCRIPTION
**Pull request by DDvO**
among others, making use of the [major CMake overhaul of libsecutils](https://github.com/siemens/libsecutils/pull/43)

### CODE REVIEW

**Comment by DDvO** [comment]
I cannot reproduce locally on my machine the CI failure of `test_all` 
using `USE_LIBCMP=1 make -f Makefile_v1 clean_all build test_all`

@rajeev, can you?

**Comment by rajeev-0** [comment]
> I cannot reproduce locally on my machine the CI failure of `test_all` using `USE_LIBCMP=1 make -f Makefile_v1 clean_all build test_all`
> 
> @rajeev, can you?

@DDvO it works fine on my machine.

**Comment by DDvO** [comment]
Good to hear that it also works for you.
Could you please try to find out (with time-boxed effort) why the CI run goes wrong
or even better find a way of tweaking the CI test such that it works there again, too?

**Comment by DDvO** [comment]
Updated submodule references zu  merged PRs hat have been just merged: 
* https://github.com/siemens/libsecutils/pull/43
* https://github.com/mpeylo/cmpossl/pull/238

**Comment by DDvO** [comment]
@rajeev-0 thank you for your CI fixes -
I've added them here, as well as a workaround for the `demo_CloudCA` server issue.
The CI seems to be sufficiently happy now :)

**Review by rajeev-0 — APPROVED** [review]
Looks good

**Pull request merged**
