### PR TITLE
`Makefile_v1` etc.: major cleanup and fixes of build system; small other updates and fixes

### PR DESCRIPTION
**Pull request by DDvO**
This was triggered by issues reported by a user attempting to build the genCMPClient on MacOS
with a very recent version of `clang` and with the typical way of installing OpenSSL there, using Homebrew.

### CODE REVIEW

**Comment by DDvO** [comment]
Further fixes added, as well as a further CI build using `Makefile_v1` and non-static libcmp.

**Comment by DDvO** [comment]
@rajeev-0, finally ready for review.

**Comment by DDvO** [comment]
@rajeev-0, since the respective PRs for the submodules are meanwhile merged,
I was able to update this PR, which is now due for review.

**Review by rajeev-0 — APPROVED** [review]
LGTM

**Pull request merged**
